Username_txtbx="//input[@placeholder='Username']"
Password_txtbx="//input[@placeholder='Password']"
SignIn_btn="//button[@type='submit']"
Dashboard_txt="//ul[@class='oxd-main-menu']/li[8]//span"
Pichart_img="(//*/div[@class='orangehrm-dashboard-widget-body'])[4]"
