Username_txtbx="//input[@placeholder='Username']"
Password_txtbx="//input[@placeholder='Password']"
SignIn_btn="//button[@type='submit']"
Dashboard_txt="//ul[@class='oxd-main-menu']/li[8]//span"
SubUnit_img="//div[@class='oxd-layout-context']/div[@class='oxd-grid-3 orangehrm-dashboard-grid']/div[6]/div[1]"
TimeAtWork_img="//div[@class='oxd-layout-context']/div[@class='oxd-grid-3 orangehrm-dashboard-grid']/div[1]/div[1]"
